### ISSUE TITLE
how to build L4T 32.1.0

### ISSUE THREAD

**Issue by gaosiy** [jetsonhacks/buildJetsonXavierKernel#1]
Hi,
   I update the jetpack 4.2 with L4T 32.1.0.
   How can I modify this build to fit the new L4T.
   Thanks a lot
gaosiy

**Comment by gaosiy** [comment]
I have finished the first 2 steps and run to 3rd step:
# Make the new Image and build the modules
I didnt change makeKernel.sh and run it, then I got the below error:

arch/arm64/mm/dma-mapping.c:1526:2: error: #error ARM Coherent DMA allocator does not (yet) support huge TLB
 #error ARM Coherent DMA allocator does not (yet) support huge TLB

can you help me?

**Comment by jetsonhacks** [comment]
It's been a while since this issue was opened. Please open another one if you continue to have issues.
